import { GoogleGenAI, Type } from "@google/genai";
import { ProductType } from '../types';

// IMPORTANT: In a real production app, never expose API keys on the client side.
// This is for demonstration purposes within the requested environment.
const apiKey = process.env.API_KEY || ''; 
const ai = new GoogleGenAI({ apiKey });

const getSystemInstruction = (agentType: ProductType): string => {
  switch (agentType) {
    case 'ebook':
      return "You are PdfForge AI, an expert author. You create detailed outlines and content for high-value non-fiction e-books.";
    case 'marketing':
      return "You are GrowthKit AI, a world-class CMO. You generate comprehensive marketing strategies and asset lists.";
    case 'automation':
      return "You are AutoFlow AI, a systems architect. You design efficient business automation workflows and SOPs.";
    case 'prompt_pack':
      return "You are PromptMaster AI, an expert prompt engineer. You craft high-fidelity prompts for LLMs and Image Generators.";
    case 'template':
      return "You are CanvasPro AI, a productivity expert. You design structured templates for business and personal organization.";
    default:
      return "You are a helpful digital product assistant.";
  }
};

export const generateProductConcept = async (agentType: ProductType, topic: string, targetAudience: string) => {
  if (!apiKey) {
    console.warn("No API Key found. Returning mock data.");
    // Mock fallback for UI testing without key
    return {
      title: `AI Generated: ${topic}`,
      description: `A complete guide customized for ${targetAudience} covering ${topic}.`,
      price: 29.99,
      features: ["Auto-generated Chapter 1", "Comprehensive Guide", "Actionable Steps"],
      toc: ["Introduction", "The Basics", "Advanced Strategies", "Conclusion"]
    };
  }

  const model = "gemini-2.5-flash";
  const systemInstruction = getSystemInstruction(agentType);
  
  const prompt = `
    Generate a digital product concept based on the topic: "${topic}" for the audience: "${targetAudience}".
    
    Return a JSON object with the following fields:
    - title (string): A catchy, professional product title.
    - description (string): A compelling 2-sentence marketing description.
    - price (number): A suggested price between 19 and 99.
    - features (array of strings): 3-5 key selling points.
    - toc (array of strings): A table of contents or list of included modules (5-8 items).
  `;

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: prompt,
      config: {
        systemInstruction: systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            title: { type: Type.STRING },
            description: { type: Type.STRING },
            price: { type: Type.NUMBER },
            features: { 
              type: Type.ARRAY,
              items: { type: Type.STRING }
            },
            toc: {
              type: Type.ARRAY,
              items: { type: Type.STRING }
            }
          }
        }
      }
    });

    if (response.text) {
      return JSON.parse(response.text);
    }
    throw new Error("No text returned from Gemini");

  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};

export const generateBlogPost = async (topic: string) => {
  if (!apiKey) {
    return {
      title: `The Future of ${topic}`,
      excerpt: `An in-depth look at how ${topic} is revolutionizing the digital landscape.`,
      content: "Lorem ipsum content generated by fallback..."
    };
  }

  const model = "gemini-2.5-flash";
  const systemInstruction = "You are an expert tech journalist and content marketer.";

  const prompt = `
    Write a blog post title, excerpt, and short content outline about: "${topic}".
    Return JSON.
  `;

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: prompt,
      config: {
        systemInstruction: systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            title: { type: Type.STRING },
            excerpt: { type: Type.STRING },
            content: { type: Type.STRING }
          }
        }
      }
    });
    
    if (response.text) return JSON.parse(response.text);
    throw new Error("No text returned");
  } catch (error) {
    console.error(error);
    throw error;
  }
};