import React, { useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useStore } from '../context/StoreContext';
import { Check, ShieldCheck, ShoppingCart, Star, Zap, ArrowLeft, Download, CreditCard } from 'lucide-react';
import { STRIPE_PAYMENT_LINK, APP_NAME } from '../constants';

const ProductDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const { products, addToCart } = useStore();
  const product = products.find(p => p.id === id);

  useEffect(() => {
    if (product?.seo?.title) {
      document.title = product.seo.title;
    } else if (product) {
      document.title = `${product.title} | ${APP_NAME}`;
    }
  }, [product]);

  if (!product) {
    return <div className="p-20 text-center text-white">Product not found</div>;
  }

  // Schema Markup (JSON-LD)
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "Product",
    "name": product.title,
    "image": product.image,
    "description": product.seo?.description || product.description,
    "sku": product.id,
    "offers": {
      "@type": "Offer",
      "url": window.location.href,
      "priceCurrency": "USD",
      "price": product.price.toString(),
      "availability": "https://schema.org/InStock"
    },
    "aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": product.rating.toString(),
      "reviewCount": product.reviews.toString()
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      {/* Inject Schema */}
      <script 
        type="application/ld+json" 
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} 
      />

      <Link to="/store" className="inline-flex items-center text-slate-400 hover:text-white mb-8 transition-colors">
        <ArrowLeft size={18} className="mr-2" /> Back to Store
      </Link>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
        {/* Left: Images */}
        <div className="space-y-6">
          <div className="aspect-square bg-slate-800 rounded-2xl overflow-hidden border border-slate-700 relative group">
            <img 
              src={product.image} 
              alt={product.seo?.altText || product.title} 
              className="w-full h-full object-cover" 
            />
            {product.isAiGenerated && (
              <div className="absolute top-4 left-4 bg-slate-950/90 backdrop-blur border border-emerald-500/50 text-emerald-400 text-xs font-bold px-3 py-1.5 rounded-full flex items-center gap-1.5">
                <Zap size={12} className="fill-emerald-400" />
                Generated by {product.agentName || 'AI Agent'}
              </div>
            )}
          </div>
        </div>

        {/* Right: Info */}
        <div>
          <div className="mb-6">
            <span className="text-emerald-400 font-semibold tracking-wide uppercase text-sm mb-2 block">
              {product.category}
            </span>
            <h1 className="text-3xl md:text-4xl font-bold text-white mb-4 leading-tight">
              {product.title}
            </h1>
            <div className="flex items-center gap-4 text-sm text-slate-400">
              <div className="flex items-center gap-1">
                <Star className="text-amber-400 fill-amber-400" size={16} />
                <span className="text-white font-medium">{product.rating}</span> 
                <span>({product.reviews} reviews)</span>
              </div>
              <span className="w-1 h-1 bg-slate-600 rounded-full"></span>
              <span>Released {product.dateAdded}</span>
            </div>
          </div>

          <div className="bg-slate-900/50 p-6 rounded-xl border border-slate-800 mb-8">
            <p className="text-slate-300 leading-relaxed text-lg">
              {product.seo?.description || product.description}
            </p>
          </div>

          <div className="mb-8">
            <h3 className="text-white font-bold mb-4">What's Inside:</h3>
            <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {product.features.map((feature, i) => (
                <li key={i} className="flex items-start gap-3 text-slate-400">
                  <Check size={18} className="text-emerald-400 mt-1 shrink-0" />
                  <span>{feature}</span>
                </li>
              ))}
            </ul>
          </div>
          
          {/* TOC for E-Books */}
          {product.category === 'ebook' && product.toc && (
             <div className="mb-8 p-6 bg-slate-900 rounded-xl border border-slate-800">
               <h3 className="text-white font-bold mb-4">Table of Contents Preview</h3>
               <ul className="space-y-2 text-sm text-slate-400">
                  {product.toc.slice(0, 5).map((item, idx) => (
                    <li key={idx} className="flex gap-3">
                      <span className="text-slate-600 font-mono">0{idx + 1}</span>
                      {item}
                    </li>
                  ))}
                  <li className="text-slate-600 italic pl-8">...and more</li>
               </ul>
             </div>
          )}

          <div className="flex flex-col sm:flex-row gap-4 pt-6 border-t border-slate-800">
            <div className="text-3xl font-bold text-white flex items-center">
              ${product.price.toFixed(2)}
            </div>
            
            <a 
              href={STRIPE_PAYMENT_LINK}
              className="flex-grow bg-emerald-500 hover:bg-emerald-600 text-white font-bold py-4 px-8 rounded-xl transition-all shadow-lg shadow-emerald-900/20 flex items-center justify-center gap-2"
            >
              <Zap size={20} />
              Buy Now
            </a>

            <button 
              onClick={() => addToCart(product)}
              className="bg-slate-800 hover:bg-slate-700 text-white font-bold py-4 px-6 rounded-xl transition-all border border-slate-700 flex items-center justify-center gap-2"
            >
              <ShoppingCart size={20} />
              Add
            </button>
            
          </div>

          <div className="mt-6 flex items-center gap-2 text-sm text-slate-500 justify-center sm:justify-start">
             <ShieldCheck size={16} />
             Secure payment via Stripe • Instant PDF Download
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProductDetail;